title: [MeToo Movement Impact Analysis]
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Has the MeToo movement affected the representation of women in the newspapers?
baseurl: "/essai" # the subpath of your site, e.g. /blog
url: "https://josephinepotdevin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  josephinepotdevin

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
